// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A placeholder Firebase configuration.
/// Replace with actual values from your Firebase Console at:
/// https://console.firebase.google.com/project/padel-shop-a94ae/settings/general
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Detect platform and return appropriate config
    return web;
  }

  // Web platform configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9UTSyZ6Dzf3w7kGI63WG8WRrCOq7zoK8',
    authDomain: 'padel-shop-a94ae.firebaseapp.com',
    projectId: 'padel-shop-a94ae',
    storageBucket: 'padel-shop-a94ae.firebasestorage.app',
    messagingSenderId: '50398158224',
    appId: '1:50398158224:web:xyz_replace_with_actual_app_id',
  );

  // Android platform configuration
  // Note: Android uses google-services.json instead (auto-generated)
  // iOS platform configuration
  // Note: iOS uses GoogleService-Info.plist instead (to be auto-generated)
}
